### ISSUE TITLE
Permit changes on streets bordering areas

### ISSUE THREAD

**Issue by XioNoX** [a-b-street/ltn#19]
Hi,

If for example we take that street : https://www.openstreetmap.org/relation/2233537

![Screenshot 2024-03-01 at 12-49-47 LTN from scratch](https://github.com/dabreegster/ltn/assets/688817/50aa6de3-b412-4faf-b747-f5e6ace69ebc)

It's currently not possible to set modal or one way filters on it as it's a zone edge. In most cases that would be fine as study areas are usually bordered by transit roads, but here the road is along a cliff. I also can't "cheat" the tool by selecting a larger study area.

Would it be possible to change that behavior ?

Thanks

**Comment by dabreegster** [comment]
This feature request makes perfect sense to me, yes. I need to maybe revisit the implementation of discovering the perimeter roads to make it work, but I'll try and look at this soon. Thanks for the idea!

**Comment by dabreegster** [comment]
![image](https://github.com/user-attachments/assets/5cfea25f-1a26-4c6c-a7de-dd8b4aa9ca86)
There's a new option to include perimeter roads for editing / shortcuts. This area is indeed tricky because of the cliff. When drawing the boundary, you can now also partly draw some freehand points if you need to stretch over more roads.
