### ISSUE TITLE
Can't access tool (404)

### ISSUE THREAD

**Issue by rouelibre1** [a-b-street/ltn#56]
Hello,

I'm getting a 404 error on https://dabreegster.github.io/ltn/

![image](https://github.com/a-b-street/ltn/assets/73238613/e13e8a20-4d3d-47c2-888d-60c129a3e00c)

Is this a known issue or maybe the tool is down for good reasons ?

**Comment by TFCx** [comment]
Same here (just for confirmation).

**Comment by dabreegster** [comment]
Hi both, sorry for the trouble! I renamed the repo, and the URL changed to https://a-b-street.github.io/ltn. Github redirects almost everything from the old name, but not GH Pages. Ultimately when this hits a first officialish version, I'd probably get a domain name hooked up for some stability, but I've had little time to work on this, sadly. Still curious about how it's working for your use cases so far and ideas for improvements.

Your saved projects should be fine because the domain hasn't changed (for local storage), but if they have, I can find instructions for copying them over.

**Comment by dabreegster** [comment]
Actually no, the subdomain changed, so your projects will disappear. To copy them over is kind of manual.

1) Go to https://dabreegster.github.io/
2) Ctrl+Shift+I (in firefox and chromium) to open developer console
3) Storage > Local Storage
4) In another tab, open the new https://a-b-street.github.io/ltn/ and do the same
5) Copy each `ltn_...` key/value over
6) Refresh the LTN tool, and it should see things

**Comment by rouelibre1** [comment]
Thanks!

It works with this domain name.

I've faced some weird geomatry/result with the selection tool on my favourite neighborhood:

![image](https://github.com/a-b-street/ltn/assets/73238613/87070c7f-8df1-45d3-ac9d-169876d549ae)


[ltn_Test.zip](https://github.com/a-b-street/ltn/files/15400756/ltn_Test.zip)

Is this something that's already on your radar ? 
Should I open a dedicated issue ?

**Comment by dabreegster** [comment]
A new issue would be good, thanks. I haven't seen anything like that before
